In [8]:
#Question 1
P=3/5
print("P(Yes/Sunny) = ",P)

P(Yes/Sunny) =  0.6


In [33]:
#Question 2
from sklearn import datasets
from sklearn import metrics
import pandas as pd
import numpy as np
import seaborn as sns

In [15]:
iris=datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [16]:
x=iris.data
y=iris.target

In [18]:
x[0:1]

array([[5.1, 3.5, 1.4, 0.2]])

In [23]:
y[0:1]

array([0])

In [24]:
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3,random_state = 0)

In [27]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB

In [28]:
gnb=GaussianNB()

In [29]:
gnb.fit(X_train,y_train)

GaussianNB(priors=None)

In [30]:
y_pred=gnb.predict(X_test)

In [31]:
score = gnb.score(X_test, y_test)
print(score)

1.0


In [34]:
confusion_matrix=metrics.confusion_matrix(y_test, y_pred)

In [35]:
print(confusion_matrix)

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [36]:
class_report=metrics.classification_report(y_test, y_pred)

In [37]:
print(class_report)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      1.00      1.00        18
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        45



In [38]:
# Now using Multinomial NB for the above dataset
mn_nb=MultinomialNB()
mn_nb.fit(X_train,y_train)
y_pred=mn_nb.predict(X_test)
score=mn_nb.score(X_test,y_test)
print(score)

0.6


In [40]:
print(metrics.confusion_matrix(y_test, y_pred))

[[16  0  0]
 [ 0  0 18]
 [ 0  0 11]]


In [41]:
print(metrics.classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.00      0.00      0.00        18
          2       0.38      1.00      0.55        11

avg / total       0.45      0.60      0.49        45



C:\Users\HP\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
