In [31]:
from sklearn import metrics
import pandas as pd
import numpy as np

In [32]:
data=pd.read_csv('titanic_train.csv')

In [33]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [22]:
data.shape

(891, 12)

In [35]:
data=data.dropna()

In [36]:
y=data['Survived']
data.drop(labels=['Survived','Embarked','Name','Ticket','Sex','Cabin'],axis=1,inplace=True)

In [37]:
data=data.dropna()

In [38]:
y.shape

(183,)

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data,y,test_size = 0.3,random_state = 0)

In [40]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier(criterion='gini')
tree.fit(X_train,y_train)
y_pred=tree.predict(X_test)

In [41]:
print(tree.score(X_test,y_test))

0.6363636363636364


In [42]:
print(metrics.confusion_matrix(y_test, y_pred))

[[ 4  9]
 [11 31]]


In [43]:
print(metrics.classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.27      0.31      0.29        13
          1       0.78      0.74      0.76        42

avg / total       0.65      0.64      0.64        55



In [44]:
tree_entropy=DecisionTreeClassifier(criterion='entropy')
tree_entropy.fit(X_train,y_train)
y_pred=tree_entropy.predict(X_test)

In [45]:
print(tree_entropy.score(X_test,y_test))

0.6


In [46]:
print(metrics.confusion_matrix(y_test, y_pred))

[[ 6  7]
 [15 27]]


In [47]:
print(metrics.classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.29      0.46      0.35        13
          1       0.79      0.64      0.71        42

avg / total       0.67      0.60      0.63        55



In [48]:
from sklearn.ensemble import RandomForestClassifier

In [49]:
random_forest=RandomForestClassifier(n_jobs=2,random_state=0,criterion='gini')


In [50]:
random_forest.fit(X_train,y_train)
y_pred=random_forest.predict(X_test)

In [51]:
print(random_forest.score(X_test,y_test))

0.6909090909090909


In [52]:
print(metrics.confusion_matrix(y_test, y_pred))

[[ 7  6]
 [11 31]]


In [53]:
print(metrics.classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.39      0.54      0.45        13
          1       0.84      0.74      0.78        42

avg / total       0.73      0.69      0.71        55



In [56]:
random_for_en=RandomForestClassifier(n_jobs=2,random_state=0,criterion='entropy')
random_for_en.fit(X_train,y_train)
y_pred=random_for_en.predict(X_test)

In [57]:
print(random_for_en.score(X_test,y_test))

0.6909090909090909


In [58]:
print(metrics.confusion_matrix(y_test, y_pred))

[[ 5  8]
 [ 9 33]]


In [59]:
print(metrics.classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.36      0.38      0.37        13
          1       0.80      0.79      0.80        42

avg / total       0.70      0.69      0.69        55

