In [1]:
from sklearn import datasets
from sklearn import metrics
import pandas as pd
import numpy as np

In [2]:
iris=datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [4]:
x=iris.data
y=iris.target

In [5]:
x[0:1]

array([[5.1, 3.5, 1.4, 0.2]])

In [6]:
y[0:1]

array([0])

In [8]:
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3,random_state = 0)

In [10]:
from sklearn.svm import SVC

In [11]:
svc_poly=SVC(kernel='poly',degree=6)
svc_poly.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=6, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
y_pred=svc_poly.predict(X_test)

In [13]:
print(svc_poly.score(X_test,y_test))

0.9777777777777777


In [14]:
print(metrics.confusion_matrix(y_test, y_pred))


[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


In [15]:
print(metrics.classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      0.94      0.97        18
          2       0.92      1.00      0.96        11

avg / total       0.98      0.98      0.98        45



In [17]:
svc_gaussian=SVC(kernel='rbf')
svc_gaussian.fit(X_train,y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [20]:
y_pred=svc_gaussian.predict(X_test)
print(svc_gaussian.score(X_test,y_test))

0.9777777777777777


In [21]:
print(metrics.confusion_matrix(y_test, y_pred))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


In [22]:
print(metrics.classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      0.94      0.97        18
          2       0.92      1.00      0.96        11

avg / total       0.98      0.98      0.98        45



In [27]:
svc_sigmoid=SVC(kernel='sigmoid')
svc_sigmoid.fit(X_train,y_train)
y_pred=svc_sigmoid.predict(X_test)
print(svc_sigmoid.score(X_test,y_test))

0.24444444444444444


In [28]:
print(metrics.confusion_matrix(y_test, y_pred))

[[ 0  0 16]
 [ 0  0 18]
 [ 0  0 11]]


In [29]:
print(metrics.classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        16
          1       0.00      0.00      0.00        18
          2       0.24      1.00      0.39        11

avg / total       0.06      0.24      0.10        45



C:\Users\HP\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [31]:
svc_linear=SVC(kernel='linear')
svc_linear.fit(X_train,y_train)
y_pred=svc_linear.predict(X_test)
print(svc_linear.score(X_test,y_test))

0.9777777777777777


In [32]:
print(metrics.confusion_matrix(y_test, y_pred))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


In [33]:
print(metrics.classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      0.94      0.97        18
          2       0.92      1.00      0.96        11

avg / total       0.98      0.98      0.98        45

